# Generated by Django 4.2.6 on 2023-10-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_alter_animal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(upload_to='media/animal_photos/'),
        ),
    ]
