# Generated by Django 4.2.6 on 2023-11-16 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shelter', '0005_shelter_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='admin',
        ),
        migrations.AddField(
            model_name='shelter',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shelter', to=settings.AUTH_USER_MODEL),
        ),
    ]
